### ISSUE TITLE
Updating the Xtext Community Website

### ISSUE THREAD

**Issue by miklossy** [LorenzoBettini/edelta#129]
Hello Edelta team,

The Xtext team would like to update the [Xtext community website](https://www.eclipse.org/Xtext/community.html) listing all the cool projects people are building around Xtext/Xtend.

See also the corresponding [GitHub issue](https://github.com/eclipse/xtext/issues/1541) and [Bugzilla ticket](https://bugs.eclipse.org/bugs/show_bug.cgi?id=328477).

If you are interested that the Edelta project is listed there, please provide the following information as a comment to this issue:

```
<tr>
	<td><a href="project_link">project_name</a></td>
	<td>project_description_max_2_sentences</td>
	<td>license</td>
	<td>category</td>
	<td>author(s)</td>
</tr>

```
We will then update the Xtext community website and get it online as soon as possible.

Thanks!
Tamás

**Comment by LorenzoBettini** [comment]
Here's the requested information and thank you!

```
<tr>
	<td><a href="project_link">https://github.com/LorenzoBettini/edelta</a></td>
	<td>An Xtext DSL for EMF metamodels refactoring and migration</td>
	<td>EPL</td>
	<td>language</td>
	<td>Lorenzo Bettini</td>
</tr>
```

**Comment by miklossy** [comment]
Thank you @LorenzoBettini !

**Comment by LorenzoBettini** [comment]
Can I close this?

**Comment by LorenzoBettini** [comment]
@miklossy I'm closing this OK?

**Comment by miklossy** [comment]
Yes, you can close this, I will take care of updating the Xtext community webpage with the information you provided.

**Comment by miklossy** [comment]
The `Edelta` project has been added to the [Xtext community website](https://www.eclipse.org/Xtext/community.html).
